### ISSUE TITLE
Add this library to conda-forge recipes

### ISSUE THREAD

**Issue by ayushkamat** [ikalnytskyi/singledispatchmethod#1]
Hello, I'm currently trying to upload a package that my company is writing to conda-forge, which depends on `singledispatchedmethod`. It doesn't seem like this package is uploaded to conda-forge, so would it be possible to also host it there alongside PyPI? I'm more than happy to take care of it myself (all it involves is adding a .yaml file in the right place), but I wanted to run this by the maintainers here to see if this is something y'all would be okay with. Thanks!

**Comment by ikalnytskyi** [comment]
Hey @ayushkamat! I have no experience with conda-forge. If all is needed is to add a YAML to this repository, please feel free to submit a pull request. I'll be happy to accept.

**Comment by ayushkamat** [comment]
Thanks for the response! It involves adding the .yaml file to [this repository](https://github.com/conda-forge/staged-recipes/tree/de39ee435acf592b7014e755ff4ef931a541a7fd). I can do this and tag you in the PR, would that be alright?

**Comment by ikalnytskyi** [comment]
Yes. Thank you!

**Comment by ikalnytskyi** [comment]
It seems it has been added.

https://github.com/conda-forge/singledispatchmethod-feedstock
